name: CD

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
        
      - name: Build wasm module
        working-directory: ./src/tilemap
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          wasm-pack build --release --no-typescript

      - name: Install and build React app
        run: |
          yarn install
          yarn build
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          # TARGET_FOLDER: jitsi_at_scale
          CLEAN: true
