name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Install node dependencies
      run: yarn install

    - name: Test React
      run: yarn test
      env:
        CI: true

    - run: cd src/tilemap

    - name: Test WASM on Chrome
      run: wasm-pack test --headless --chrome

    - name: Test WASM on Firefox
      run: wasm-pack test --headless --firefox
